name: Build Go binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build -o gscan

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: gscan
        path: gscan
